[project]
authors = ["Igor Rončević"]
entry = "lib.sw"
license = "MIT"
name = "test_lib"
# implicit-std = false

[dependencies]
# core = { path = "../../../../sway/sway-lib-core" }
std = { path = "../../../../sway/sway-lib-std" }
