[project]
authors = ["Kebradalaonda"]
entry = "main.sw"
license = "Apache-2.0"
name = "temp_contract"

[dependencies]
# core = { path = "../../sway/sway-lib-core" }
# std = { path = "../../sway/sway-lib-std" }

