[project]
authors = ["Igor Rončević"]
entry = "main.sw"
license = "MIT"
name = "declare_references"

[dependencies]
core = { path = "../../sway/sway-lib-core" }
std = { path = "../../sway/sway-lib-std" }

