[package]
name = "rust_format_vs_concat"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "string_concat_bench"
harness = false
