[package]
name = "hashing"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2   = "0.10"
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
hex    = "0.4"
bincode = "1.3"
serde  = { version = "1", features = ["derive"] }  # Needed by bincode
