[project]
authors = ["Igor Rončević"]
entry = "main.sw"
license = "MIT"
name = "sample-project"
# implicit-std = false

[dependencies]
# core = { path = "../../sway/sway-lib-core" }
# std = { path = "../../sway/sway-lib-std" }
core = { path = "/home/kebradalaonda/p/sway/sway-lib-core" }
std = { path = "/home/kebradalaonda/p/sway/sway-lib-std" }
