[project]
authors = ["Igor Rončević"]
entry = "main.sw"
license = "MIT"
name = "plays"
# implicit-std = false

[dependencies]
# core = { path = "../../../sway/sway-lib-core" }
# std = { path = "../../../sway/sway-lib-std" }
std = { path = "../../../sway/test/src/e2e_vm_tests/reduced_std_libs/sway-lib-std-assert" }
