[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "test_lib" # Same name as the imported lib and this compiles.
implicit-std = false

[dependencies]
test_lib = { path = "../test_lib/" }