[project]
authors = ["Igor Rončević"]
entry = "main.sw"
license = "MIT"
name = "global_consts"
# implicit-std = false

[dependencies]
# core = { path = "../../../../sway/sway-lib-core" }
std = { path = "../../../../sway/sway-lib-std" }
